baseURL = 'https://www.houseofguineas.com'
languageCode = 'en-us'
title = 'House of Guineas: San Francisco & Peninsula Exotic Pet Care'
theme = 'hugo-initio'
style = 'default'
enableGitInfo = true

[frontmatter]
  lastmod = [':git', 'lastmod', 'date']

[sitemap]
  changefreq = 'weekly'
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This setting allows you to use raw HTML in your Markdown files.
      # It is required for the <details> and <summary> tags to work.
      unsafe = true
      
[params]
name = "House of Guineas Pet Care"
description = "San Francisco & Peninsula's Exotic Pet Professionals"
email = "petcare@houseofguineas.com"
phone = "415-484-6493"
# address = "San Francisco, CA"
address = "San Francisco & Peninsula's exotic pet specialists — in-home care across SF, Burlingame, San Mateo, Millbrae, Hillsborough, Foster City, Redwood City and surrounding areas. Boarding hosted in San Francisco."
avatar = "prof.jpeg"
avatarclass = "circle"
background = ""
banner = "milo.jpeg"
favicon = "images/gt_favicon.png"
DateForm = "January 2, 2006"
author = "House of Guineas Pet Care"

showSubheader = true
showServices = true
showRecentWorks = false
# added reviews
showReviews = true
showDownloads = true
showClients = true
showProduct = true

showFooterContact = true
showFooterFollowMe = true
showFooterTextWidget = false
showFooterFormWidget = false

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 6
# added to include sub menu for resources in bay area
[[menu.main]]
  name = "Resources"
   url = "/resources/"
  identifier = "resources"
  weight = 5
#   to concatenate services boardinfg and inhome on the menu par
[[menu.main]]
  name = "Services and Rates"
   url = "/services/"
  identifier = "rates"
  weight = 2
[[menu.main]]
  name = "Clinical Series Liners"
  url = "/clinical-series-fleece-cage-liners/"
  identifier = "clinical"
  weight = 3

[params.sharethis]
property = "123456789012345678901234"
custom = true

[params.google.analytics]
trackerID = "G-6JZQ3G0Q5M"

[[params.social]]
title = "tiktok"
url = "https://www.tiktok.com/@houseofguineas"
icon = "fa-brands fa-tiktok"
footer = true
sharethis = false
network = "tiktok"

[[params.social]]
title = "instagram"
url = "https://www.instagram.com/houseofguineas?igsh=OGQ5ZDc2ODk2ZA=="
icon = "fa-brands fa-instagram"
footer = true
sharethis = false
network = "instagram"

[[params.social]]
title = "youtube"
url = "https://www.youtube.com/@houseofguineas"
icon = "fa-brands fa-youtube"
footer = true
sharethis = false
network = "youtube"

[[params.social]]
title = "linkedin"
url = "https://www.linkedin.com/in/alexandria-b-65b845100/"
icon = "fa-brands fa-linkedin"
footer = false
sharethis = false
network = "linkedin"

[[params.social]]
title = "email"
url = "mailto:petcare@houseofguineas.com"
icon = "fa-regular fa-envelope"
footer = false
sharethis = false
network = "email"